language: bash

dist: xenial

before_install:
  - rm -rf ~/.gnupg

before_script:
  - sudo apt-get -qq autoremove
  - sudo apt-get update -q

script:
  - lsb_release -a
  - sudo echo "Travis Banch = $TRAVIS_BRANCH"
  - sudo bash wo-nginx-setup.sh $TRAVIS_BRANCH
  - sudo wo site create wordops.org --wp || sudo tail -n50 /var/log/wo/wo.log
  - sudo wo site create wordops.io --mysql || sudo tail -n50 /var/log/wo/wo.log
  - sudo nginx -t

