language: bash

dist: xenial

before_install:
  - rm -rf ~/.gnupg

before_script:
  - sudo rm -rf /etc/mysql/
  - sudo apt-get -qq purge mysql* graphviz*
  - sudo apt-get -qq autoremove
  - sudo apt-get update -q

script:
  - lsb_release -a
  - sudo echo "Travis Banch = $TRAVIS_BRANCH"
  - sudo bash wo-nginx-setup.sh --travis $TRAVIS_BRANCH || sudo tail -n 100 /var/log/wo/wordops.log
  - sudo wo site create wordops.org --wp || sudo tail -n 100 /var/log/wo/wordops.log
  - sudo wo site create wordops.io --mysql || sudo tail -n 100 /var/log/wo/wordops.log


